const ghosts = [
  {
    name: 'Banshee',
    evidences: ['Ultraviolett', 'DOTS', 'Geisterorbs'],
    huntClass: 'normal',
    huntValue: 'zielabhängig',
    tags: ['100%-Test', 'Audio'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '33% Schrei-Chance; 15% Sanity bei singendem Event aufs Hauptziel.',
    keyTest: 'Mit Parabolmikro oder Sound Recorder auf den einzigartigen Banshee-Schrei achten. Das ist ihr klarster Solo-Test.',
    huntNote: 'Jagd richtet sich nur nach der Sanity ihres Hauptziels. Ist das Ziel nicht im Haus, kann sie trotzdem andere Spieler töten.',
    specialNote: 'Wählt ein Hauptziel und folgt diesem auch weit weg vom Geisterraum. Im DOTS läuft sie bevorzugt auf dieses Ziel zu.',
    caution: 'Nicht nur auf normale Events achten. Schrei, Zielverhalten und singende Events zusammen lesen.'
  },
  {
    name: 'Dayan',
    evidences: ['EMF Level 5', 'Geisterorbs', 'Geisterbox'],
    huntClass: 'frueh',
    huntValue: '45 bis 60%',
    tags: ['Jagdtest', 'Bewegung'],
    speedValue: '1,2 / 1,7 / 2,25 m/s',
    speedHint: 'Bewegung in der Nähe verändert alles',
    percentInfo: '60% mit Bewegung; 45% ohne Bewegung in Nähe; 50% ohne Spieler nahebei.',
    keyTest: 'Bewege dich in ihrer Nähe und vergleiche direkt den Hunt: mit Bewegung im 10-m-Umkreis wird sie schnell, ohne Bewegung ungewöhnlich langsam.',
    huntNote: 'Ohne Bewegung etwa 1,2 m/s, normal 1,7 m/s, mit Bewegung bis 2,25 m/s. Jagen kann sie je nach Spielernähe schon ab 60%.',
    specialNote: 'Immer weiblicher Geist. Ohne Spieler in der Nähe liegt die normale Jagdgrenze bei 50%.',
    caution: 'Nur vergleichbare Hunts werten. Ein Hunt mit Bewegung und einer ohne Bewegung müssen direkt gegeneinander gelesen werden.'
  },
  {
    name: 'Dämon',
    evidences: ['Ultraviolett', 'Geisterbuch', 'Gefriertemperaturen'],
    huntClass: 'frueh',
    huntValue: '70% / Fähigkeit auch darüber',
    tags: ['Fast sicher', 'Räucherwerk'],
    speedValue: '1,7 m/s',
    speedHint: 'Normal, aber extrem jagdfreudig',
    percentInfo: '70% normal; 50% mehr Kruzifix-Reichweite; 20% weniger Cursed-Drain.',
    keyTest: 'Sehr frühe Jagd oder ein neuer Hunt schon 60 Sekunden nach Räucherwerk deutet stark auf Dämon. Das ist sein sauberster Praxistest.',
    huntNote: 'Normales Tempo, aber nur 20 Sekunden Hunt-Cooldown statt 25. Über seine Fähigkeit kann er auch über 70% jagen.',
    specialNote: 'Kruzifixe haben 50% mehr Reichweite. Ohne Räuchern kann er schon nach 20 statt 25 Sekunden wieder jagen; verfluchte Besitztümer ziehen 20% weniger Sanity ab.',
    caution: 'Frühe Jagd allein reicht nicht. Immer Smudge-Timer oder Kruzifix-Reichweite gegenprüfen.'
  },
  {
    name: 'Deogen',
    evidences: ['Geisterbox', 'Geisterbuch', 'DOTS'],
    huntClass: 'normal',
    huntValue: '40%',
    tags: ['100%-Test', 'Anti-Hide'],
    speedValue: '0,4 bis 3,0 m/s',
    speedHint: 'Weit schnell, direkt bei dir extrem langsam',
    percentInfo: '40% Jagdgrenze; 33% Deogen-Atem bei <1 m Spirit Box.',
    keyTest: 'Auf das einzigartige Deogen-Atmen in der Spirit Box achten. Im Hunt direkt an ihm vorbeilaufen: in Nähe wird er extrem langsam.',
    huntNote: 'Über 6 m Entfernung bis 3,0 m/s, in direkter Nähe bis 0,4 m/s langsam. Er beschleunigt nicht normal.',
    specialNote: 'Findet Spieler in Hunts praktisch immer und antwortet in der Spirit Box auch bei weniger als 3 Beweisen.',
    caution: 'Nicht verstecken. Sein Nah-Tempo ist viel verlässlicher als nur auf das Atmen zu warten.'
  },
  {
    name: 'Gallu',
    evidences: ['EMF Level 5', 'Ultraviolett', 'Geisterbox'],
    huntClass: 'normal',
    huntValue: '40 / 50 / 60%',
    tags: ['Jagdtest', 'Zustände'],
    speedValue: '1,36 / 1,7 / 1,96 m/s',
    speedHint: 'Schwach, normal oder aggressiv',
    percentInfo: '40/50/60% Jagdgrenze; 20% kürzere aggressive Jagd; Kruzifix -2 m/+1 m.',
    keyTest: 'Mit Salz, verbranntem Kruzifix oder Räucherwerk den Zustand provozieren. Wechseln Jagdgrenze und Tempo klar, passt das stark zu Gallu.',
    huntNote: 'Schwach 1,36 m/s und 40%, normal 1,7 m/s und 50%, aggressiv 1,96 m/s und 60%.',
    specialNote: 'Startet normal. Verwischtes Salz oder verbranntes Kruzifix kann ihn aggressiv machen, ein Hunt-Ende im aggressiven Zustand kann ihn schwächen.',
    caution: 'Nie nur einen einzelnen Hunt werten. Gallu lebt von Zustandswechseln.'
  },
  {
    name: 'Goryo',
    evidences: ['EMF Level 5', 'Ultraviolett', 'DOTS'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['100%-Test', 'Kamera'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '50% Standard; DOTS bleibt bei weniger als 3 Beweisen immer erhalten.',
    keyTest: 'DOTS nur über Videokamera prüfen, wenn kein Spieler im gleichen Raum steht. Das ist das markanteste Goryo-Merkmal.',
    huntNote: 'Normale Jagd und normales Tempo. Erkennbar ist Goryo eher über Verhalten als über Hunts.',
    specialNote: 'Wechselt den Geisterraum praktisch nie, wandert kaum weit weg und behält bei weniger als 3 Beweisen immer DOTS.',
    caution: 'Mit bloßem Auge testet man ihn oft falsch. Für DOTS wirklich Kamera und Abstand nutzen.'
  },
  {
    name: 'Hantu',
    evidences: ['Ultraviolett', 'Geisterorbs', 'Gefriertemperaturen'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['100%-Test', 'Strom'],
    speedValue: '1,4 bis 2,7 m/s',
    speedHint: 'Je kälter der Raum, desto schneller',
    percentInfo: '50% Standard; doppelte Chance auf Stromausfall.',
    keyTest: 'Strom aus und im Hunt auf sichtbaren Atem achten. Dazu Tempo in kalten und warmen Räumen vergleichen.',
    huntNote: 'Bei 0 °C bis 2,7 m/s, in warmen Räumen etwa 1,4 m/s. Keine Sichtlinien-Beschleunigung.',
    specialNote: 'Schaltet den Strom gern aus, hat doppelte Chance auf Stromausfall und behält bei weniger als 3 Beweisen weiterhin Gefriertemperaturen.',
    caution: 'Atem ist nur während der Jagd aussagekräftig und nur bei Strom aus ein starkes Hantu-Merkmal.'
  },
  {
    name: 'Dschinn',
    evidences: ['EMF Level 5', 'Ultraviolett', 'Gefriertemperaturen'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Fast sicher', 'Sichtlinie', 'Strom'],
    speedValue: '1,7 / 2,5 m/s',
    speedHint: 'Mit Strom auf Distanz plötzlich schnell',
    percentInfo: '50% Standard; 25% Sanity-Drain durch Fähigkeit.',
    keyTest: 'Strom anlassen und Distanz schaffen. Wird der Geist bei Sichtkontakt ab über 3 m plötzlich 2,5 m/s schnell, ist Dschinn sehr wahrscheinlich.',
    huntNote: 'Nur mit Strom an und auf Distanz schnell. Ohne Strom bleibt er bei normalem Tempo.',
    specialNote: 'Kann den Sicherungskasten nicht selbst ausschalten. Seine Fähigkeit kann am Kasten EMF auslösen und Spielern im selben Raum in 3 m Umkreis 25% Sanity ziehen.',
    caution: 'Nicht mit Raiju verwechseln. Dschinn hängt an Strom plus Distanz, nicht an aktiver Elektronik.'
  },
  {
    name: 'Mare',
    evidences: ['Geisterbox', 'Geisterbuch', 'Geisterorbs'],
    huntClass: 'frueh',
    huntValue: '40% im Licht / 60% im Dunkeln',
    tags: ['Fast sicher', 'Licht'],
    speedValue: '1,7 m/s',
    speedHint: 'Tempo normal, Licht ist entscheidend',
    percentInfo: '60% im Dunkeln; 40% im Licht; 10 s Cooldown auf Lichtschalter-Fähigkeit.',
    keyTest: 'Licht im Geisterraum anschalten: schaltet der Geist den Schalter sofort wieder aus oder jagt nur im Dunkeln früh, ist Mare sehr wahrscheinlich.',
    huntNote: 'Im Dunkeln schon ab 60%, im beleuchteten Raum erst ab 40%. Tempo bleibt normal.',
    specialNote: 'Kann keine Lichter einschalten, bevorzugt das Ausschalten von Licht, wandert gern in dunkle Räume und zerstört bei Events häufiger Glühbirnen.',
    caution: 'Nicht nur ein ausgeschaltetes Licht werten. Raumhelligkeit und Jagdschwelle zusammen lesen.'
  },
  {
    name: 'Moroi',
    evidences: ['Geisterbox', 'Geisterbuch', 'Gefriertemperaturen'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Jagdtest', 'Audio'],
    speedValue: '1,5 bis 2,25 m/s',
    speedHint: 'Je weniger Sanity, desto schneller',
    percentInfo: '50% = 1,5 m/s; 0% = 2,25 m/s; Räucherwerk 50% länger.',
    keyTest: 'Fluch über Spirit Box, Parabolmikro oder Sound Recorder auslösen und dann die Sanity beobachten. Mit fallender Sanity wird er deutlich schneller.',
    huntNote: 'Bei 50% etwa 1,5 m/s, bei 0% bis 2,25 m/s. Räucherwerk wirkt bei ihm 50% länger.',
    specialNote: 'Verflucht Spieler. Spirit Box, Parabolmikro und Sound Recorder können den Fluch auslösen; Sanity-Medizin hebt ihn auf, Verlassen des Hauses pausiert ihn.',
    caution: 'Tempo nie ohne Sanity-Kontext lesen. Genau das ist der Kern beim Moroi.'
  },
  {
    name: 'Myling',
    evidences: ['EMF Level 5', 'Ultraviolett', 'Geisterbuch'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Fast sicher', 'Audio'],
    speedValue: '1,7 m/s',
    speedHint: 'Normal schnell, aber spät hörbar',
    percentInfo: '50% Standard; Hunt-Sound erst etwa ab 12 m statt 20 m.',
    keyTest: 'Im Hunt auf die Hörweite achten: Schritte und Stimme hörst du erst ab etwa 12 m statt ab 20 m. Das ist sein bestes Merkmal.',
    huntNote: 'Normales Tempo und normale Jagdgrenze. Er fällt fast nur durch spät hörbares Hunt-Audio auf.',
    specialNote: 'Gibt häufiger paranormale Geräusche über Parabolmikro und Sound Recorder.',
    caution: 'Nicht nach Bauchgefühl testen. Distanz, Stockwerke und Wandlautstärke können den Eindruck verfälschen.'
  },
  {
    name: 'Obake',
    evidences: ['EMF Level 5', 'Geisterorbs', 'Ultraviolett'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['100%-Test', 'Täuscher'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '75% normale UV-Chance; 17% Spezialabdruck; 6,66% Modellwechsel pro Blink.',
    keyTest: 'Auf den einzigartigen Fingerabdruck achten oder im Hunt auf den kurzen Modellwechsel. Beides identifiziert Obake am sichersten.',
    huntNote: 'Normales Jagdtempo. Sein Hunt-Merkmal ist nicht Speed, sondern der Modellwechsel.',
    specialNote: 'UV-Spuren erscheinen nur in etwa 75% der Fälle und halten nur halb so lang. Der Modellwechsel kann im Hunt einmal garantiert vorkommen.',
    caution: 'Fehlende UV-Spur schließt Obake nicht aus. Besser auf Spezialabdruck oder Modellwechsel warten.'
  },
  {
    name: 'Obambo',
    evidences: ['Geisterbuch', 'Ultraviolett', 'DOTS'],
    huntClass: 'frueh',
    huntValue: '10% ruhig / 65% aggressiv',
    tags: ['Jagdtest', 'Zustände'],
    speedValue: '1,45 / 1,96 m/s',
    speedHint: 'Ruhiger und aggressiver Zustand',
    percentInfo: '10% ruhig; 65% aggressiv; aggressive Jagden 20% kürzer.',
    keyTest: 'Nach dem Öffnen der Haustür den Timer beobachten: startet er nach etwa 1 Minute in den aggressiven Zustand und wechselt später wieder, passt das stark zu Obambo.',
    huntNote: 'Ruhiger Zustand etwa 1,45 m/s und 10%, aggressiver Zustand etwa 1,96 m/s und 65%.',
    specialNote: 'Startet immer ruhig. Wechselt etwa 1 Minute nach Öffnen der Haustür erstmals aggressiv und danach etwa alle 2 Minuten den Zustand, auch mitten in der Jagd. Aggressive Hunts dauern kürzer.',
    caution: 'Nicht mit Zwillingen verwechseln. Obambo wechselt den Gesamtzustand, nicht nur einzelne Interaktionen.'
  },
  {
    name: 'Oni',
    evidences: ['EMF Level 5', 'DOTS', 'Gefriertemperaturen'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Fast sicher', 'Events'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '50% Standard; 20% Sanity-Verlust bei Geister-Events.',
    keyTest: 'Geister-Events beobachten: Oni macht keine Nebelgestalt und bleibt im Hunt länger sichtbar als andere Geister.',
    huntNote: 'Normales Tempo. Er sticht über Sichtbarkeit und hohe Aktivität hervor, nicht über Jagdtempo.',
    specialNote: 'Sehr aktiv in Spielernähe, bevorzugt volle Manifestationen, macht keine Nebelgestalten und zieht bei Geister-Events 20% Sanity.',
    caution: 'Hohe Aktivität allein reicht nicht. Der fehlende Airball ist der bessere Gegencheck.'
  },
  {
    name: 'Onryo',
    evidences: ['Geisterbox', 'Geisterorbs', 'Gefriertemperaturen'],
    huntClass: 'sehr-frueh',
    huntValue: '40% mit Flamme / Fähigkeit bis 100%',
    tags: ['100%-Test', 'Flammen'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '40% mit Flamme; Fähigkeit theoretisch bis 100%; 3 Flammen lösen Test aus.',
    keyTest: 'Drei gelöschte Flammen mitzählen und dann innerhalb weniger Sekunden auf einen Hunt achten. Das ist der klarste Onryo-Test.',
    huntNote: 'Mit Flamme in 4 m Nähe sinkt die normale Jagdgrenze auf 40%, über die Fähigkeit kann er aber theoretisch schon bei 100% jagen.',
    specialNote: 'Kerzen haben bei ihm höhere Priorität als Kruzifixe. Brennt eine Flamme in 4 m, blockt sie Hunts komplett.',
    caution: 'Kerzen sauber mitzählen. Ein einzelnes Auspusten reicht für den Test noch nicht.'
  },
  {
    name: 'Phantom',
    evidences: ['Geisterbox', 'DOTS', 'Ultraviolett'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['100%-Test', 'Foto'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '50% Standard; 0,5% Sanity-Verlust pro Sichtkontakt-Tick in 10 m.',
    keyTest: 'Foto oder Video machen: verschwindet der Geist dabei, ist es ein Phantom. Das ist viel sicherer als nur auf das Blinken zu achten.',
    huntNote: 'Normales Tempo, aber während der Jagd nur kurze seltene Sichtfenster etwa alle 1 bis 2 Sekunden.',
    specialNote: 'Teleportiert sich zur letzten Position eines zufälligen Spielers, erzeugt dort EMF und zieht bei Sichtkontakt in 10 m Umkreis zusätzlich Sanity.',
    caution: 'Blinken allein nicht überwerten. Der Foto-Test ist deutlich sicherer.'
  },
  {
    name: 'Poltergeist',
    evidences: ['Geisterbox', 'Ultraviolett', 'Geisterbuch'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Fast sicher', 'Objekte'],
    speedValue: '1,7 m/s',
    speedHint: 'Tempo normal, Umgebung verrät ihn',
    percentInfo: '50% Standard; 2% Sanity pro Wurfobjekt-Treffer; 100% Wurfchance alle 0,5 s im Hunt.',
    keyTest: 'Einen Raum mit vielen Objekten vorbereiten und auf Mehrfachwürfe oder extrem kräftige Würfe achten. Das ist sein klarster Test.',
    huntNote: 'Normale Jagdgrenze und normales Tempo. Im Hunt kann er alle 0,5 Sekunden garantiert ein Objekt werfen, wenn genug herumliegt.',
    specialNote: 'Kann mehrere Objekte gleichzeitig werfen, erzeugt dabei EMF 2 und zieht pro getroffenem Wurfobjekt 2% Sanity.',
    caution: 'In leeren Räumen ist er fast unsichtbar. Für einen sauberen Test immer genug Wurfobjekte liegen lassen.'
  },
  {
    name: 'Raiju',
    evidences: ['EMF Level 5', 'Geisterorbs', 'DOTS'],
    huntClass: 'frueh',
    huntValue: '50% normal / 65% mit Geräten',
    tags: ['Fast sicher', 'Strom'],
    speedValue: '1,7 / 2,5 m/s',
    speedHint: 'An aktiver Elektronik plötzlich schnell',
    percentInfo: '65% mit aktiven Geräten; Interferenz-Radius 15 m; Geräte-Reichweite 6/8/10 m.',
    keyTest: 'Aktive Elektronik bewusst hinlegen und den Hunt beobachten: wird er in Gerätenähe plötzlich 2,5 m/s schnell, ist Raiju sehr wahrscheinlich.',
    huntNote: 'An eingeschalteten Geräten bis 2,5 m/s und Jagdgrenze bis 65%, sonst normales Tempo.',
    specialNote: 'Paranormale Interferenz reicht bis etwa 15 m. Kleine, mittlere und große Geräte triggern ihn in etwa 6 m, 8 m und 10 m Reichweite.',
    caution: 'Vor dem Test Elektronik bewusst platzieren. Sonst wirken zufällige Geräte wie falsche Speed-Hinweise.'
  },
  {
    name: 'Revenant',
    evidences: ['Geisterorbs', 'Geisterbuch', 'Gefriertemperaturen'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Fast sicher', 'Sichtlinie'],
    speedValue: '1,0 / 3,0 m/s',
    speedHint: 'Ohne Zielwissen langsam, mit Zielwissen extrem schnell',
    percentInfo: '50% Standard; 1,0 m/s ohne Zielwissen; 3,0 m/s mit Zielwissen; 2,7 s Abbremsen.',
    keyTest: 'Einen Hunt aus sicherem Versteck beobachten: mit Zielwissen sprintet er brutal schnell, ohne Zielwissen schleicht er fast nur.',
    huntNote: 'Etwa 1,0 m/s ohne Wissen über deinen Ort, bis 3,0 m/s mit Zielwissen. Keine normale Beschleunigung.',
    specialNote: 'Bremst nach verlorenem Zielwissen innerhalb von etwa 2,7 Sekunden wieder stark ab.',
    caution: 'Nie offen testen. Revenant sollte immer mit sicherem Sichtbruch oder Versteck geprüft werden.'
  },
  {
    name: 'Shade',
    evidences: ['EMF Level 5', 'Geisterbuch', 'Gefriertemperaturen'],
    huntClass: 'spaet',
    huntValue: '35%',
    tags: ['Fast sicher', 'Passiv'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo, aber sehr passiv',
    percentInfo: '35% Jagdgrenze; 0% Event-Chance bei 100% Sanity; 100% bei 50% Sanity.',
    keyTest: 'Länger im Geisterraum bleiben: passiert mit Spielern im Raum fast nichts und jagt er nie im selben Raum, ist Shade sehr naheliegend.',
    huntNote: 'Jagt erst bei 35% und nicht im selben Raum wie Spieler. Tempo bleibt normal.',
    specialNote: 'Ist mit Spielern im Raum extrem inaktiv, macht keine EMF-3-Aktionen im selben Raum und bevorzugt Schatten- oder Wolken-Manifestationen.',
    caution: 'Ein ruhiges Match allein reicht nicht. Immer Abstand und Aktivität im Geisterraum mitprüfen.'
  },
  {
    name: 'Spirit',
    evidences: ['EMF Level 5', 'Geisterbox', 'Geisterbuch'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Fast sicher', 'Räucherwerk'],
    speedValue: '1,7 m/s',
    speedHint: 'Komplett normal, nur Smudge verrät ihn',
    percentInfo: '50% Standard; 180 s Smudge-Sperre statt 90 s normal.',
    keyTest: 'Räucherwerk nutzen und 180 Sekunden stoppen. Kommt in dieser Zeit sicher kein Hunt, spricht das stark für Spirit.',
    huntNote: 'Normale Jagdgrenze und normales Tempo. Sein einzig wirklich starkes Hunt-Merkmal ist das lange Smudge-Fenster.',
    specialNote: 'Ohne Smudge-Test bleibt Spirit oft nur als Ausschluss übrig.',
    caution: 'Nicht mit Dämon verwechseln. Den Timer sauber stoppen, sonst ist der Test wertlos.'
  },
  {
    name: 'Thaye',
    evidences: ['Geisterorbs', 'DOTS', 'Geisterbuch'],
    huntClass: 'sehr-frueh',
    huntValue: '15 bis 75%',
    tags: ['Fast sicher', 'Alterung'],
    speedValue: '1,0 bis 2,75 m/s',
    speedHint: 'Altert und wird immer schwächer',
    percentInfo: '75% jung; 15% alt; Event/Interaktionswerte sinken bis 50%.',
    keyTest: 'Frühes Match mit spätem Match vergleichen: anfangs extrem aktiv und schnell, später deutlich harmloser, passt sehr stark zu Thaye.',
    huntNote: 'Jagt am Anfang sehr früh und schnell, mit Alterung sinken Jagdgrenze, Aktivität und Tempo stark.',
    specialNote: 'Altert nur mit Spielern in seiner Nähe. Voll gealtert fällt er bis auf 15% Jagdgrenze und 1,0 m/s; mit dem Ouija Board kann man seine Altersstufe testen.',
    caution: 'Frühe und späte Beobachtungen nie mischen. Zeit im Geisterraum ist bei Thaye alles.'
  },
  {
    name: 'Der Mimik',
    evidences: ['Geisterbox', 'Ultraviolett', 'Gefriertemperaturen'],
    fakeVisibleEvidence: ['Geisterorbs'],
    huntClass: 'normal',
    huntValue: 'kopiert den imitierten Geist',
    tags: ['100%-Test', 'Täuscher'],
    speedValue: 'kopiert den imitierten Geist',
    speedHint: 'Hunt-Verhalten wechselt mit der Kopie',
    percentInfo: 'Wechselt Kopie alle 30 bis 120 s; erste Minute ohne Imitation.',
    keyTest: 'Immer auf zusätzliche sichtbare Orbs achten. Tauchen Orbs auf, aber die echten Beweise passen nicht, ist es oft der Mimik.',
    huntNote: 'Kann Jagdtempo, Sanity-Grenze und Verhalten anderer Geister übernehmen. Ein einzelner Hunt sagt deshalb fast nichts aus.',
    specialNote: 'Besitzt immer Fake-Orbs, die nie als echter Beweis zählen. Wechselt die Kopie regelmäßig außerhalb der Jagd und imitiert in der ersten Minute keinen Geist.',
    caution: 'Nie nur einen einzigen Test werten. Beim Mimik müssen Beweise, Fake-Orbs und mehrere Hunts zusammen gelesen werden.'
  },
  {
    name: 'Die Zwillinge',
    evidences: ['EMF Level 5', 'Geisterbox', 'Gefriertemperaturen'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['Fast sicher', 'Doppelaktion'],
    speedValue: '1,53 / 1,87 m/s',
    speedHint: 'Zwei feste Hunt-Speeds',
    percentInfo: '50% Chance, welcher Zwilling jagt; Nebenzwilling max. 16 m entfernt.',
    keyTest: 'Auf weit getrennte Doppelinteraktionen achten oder zwei klar verschiedene Jagdgeschwindigkeiten hören. Genau das verrät die Zwillinge.',
    huntNote: 'Hauptzwilling etwa 1,53 m/s, Nebenzwilling etwa 1,87 m/s.',
    specialNote: 'Nebenzwilling kann nur EMF geben und jagen und bleibt maximal etwa 16 m vom Hauptzwilling entfernt. Kruzifixe wirken nur am Hauptzwilling.',
    caution: 'Nicht mit Zufall verwechseln. Die Distanz zwischen Interaktionen und die zwei festen Speeds sind entscheidend.'
  },
  {
    name: 'Gespenst',
    evidences: ['EMF Level 5', 'DOTS', 'Geisterbox'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['100%-Test', 'Salz'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '50% Standard; Teleport erzeugt EMF 2/5 am Zielpunkt.',
    keyTest: 'Salz legen: tritt der Geist hinein, ohne verwischte Salzspuren zu hinterlassen, ist das der sichere Gespenst-Test.',
    huntNote: 'Normale Jagdgrenze und normales Tempo.',
    specialNote: 'Kann sich im Umkreis von 3 m zu Spielern teleportieren und am Zielpunkt EMF 2/5 erzeugen.',
    caution: 'Salz muss sauber platziert sein. Ohne guten Salztest ist Gespenst schwer sicher zu identifizieren.'
  },
  {
    name: 'Yokai',
    evidences: ['Geisterbox', 'DOTS', 'Geisterorbs'],
    huntClass: 'sehr-frueh',
    huntValue: '50% normal / 80% beim Sprechen',
    tags: ['Fast sicher', 'Audio'],
    speedValue: '1,7 m/s',
    speedHint: 'Normal, aber Stimme provoziert Hunts',
    percentInfo: '80% beim Sprechen nahebei; Wahrnehmung im Hunt oft erst unter 2 m.',
    keyTest: 'Nah am Geist sprechen und auf frühe Aktivität oder einen Hunt achten. Im Hunt ortet Yokai Stimmen und Elektronik erst auf sehr kurze Distanz.',
    huntNote: 'Kann durch Sprechen in unmittelbarer Nähe bis 80% jagen. In Hunts ortet er Stimmen und Geräte oft erst unter 2 m.',
    specialNote: 'Sehr gutes Ziel für Voice-Tests. Sprechen in unmittelbarer Nähe erhöht Aktivität und Jagdchance; auch die Musikbox startet erst aus sehr kurzer Distanz.',
    caution: 'Nur mit ruhigem Team testen. Zu viel Gerede macht Yokai schnell schwer lesbar.'
  },
  {
    name: 'Yurei',
    evidences: ['Geisterorbs', 'DOTS', 'Gefriertemperaturen'],
    huntClass: 'normal',
    huntValue: '50%',
    tags: ['100%-Test', 'Türen'],
    speedValue: '1,7 m/s',
    speedHint: 'Standardtempo',
    percentInfo: '50% Standard; 14% Sanity bei Tür-Fähigkeit; 90 s Wanderstopp nach Smudge.',
    keyTest: 'Auf den speziellen Tür-Slam achten und danach mit Räucherwerk prüfen: 90 Sekunden lang nicht zu wandern ist sein sauberster Test.',
    huntNote: 'Normale Jagdgrenze und normales Tempo.',
    specialNote: 'Kann eine Tür komplett schließen und dabei 14% Sanity ziehen. Ist der einzige Geist, der aktiv die Haustür nutzen kann; Türen bewegt er nie nur ein wenig.',
    caution: 'Normale Türbewegung zählt nicht. Es geht nur um den klaren Slam oder den Smudge-Wanderstopp.'
  }
];


